# Generated by Django 5.2.8 on 2025-12-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_real_time',
            field=models.BooleanField(default=False),
        ),
    ]
