# Generated by Django 5.2.8 on 2025-12-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subasta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subasta.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='subasta.auctionitem'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subasta.item'),
        ),
        migrations.AddField(
            model_name='auction',
            name='items',
            field=models.ManyToManyField(related_name='auctions', through='subasta.AuctionItem', to='subasta.item'),
        ),
        migrations.AddField(
            model_name='itemgranted',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subasta.auctionitem'),
        ),
        migrations.AddField(
            model_name='itemgranted',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
