# Generated by Django 5.2.8 on 2025-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0002_auction_is_real_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('Todas', 'Todas'), ('Arte y Antigüedades', 'Arte y Antigüedades'), ('Tecnología', 'Tecnología'), ('Joyería', 'Joyería'), ('Vehículos', 'Vehículos'), ('Muebles', 'Muebles'), ('Coleccionables', 'Coleccionables'), ('Ropa y Accesorios', 'Ropa y Accesorios'), ('Deportes', 'Deportes')], default='Todas', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='itemgranted',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed'), ('Dispute', 'Dispute')], default='Pending', max_length=10),
        ),
    ]
